# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import lipsyncsrv_pb2 as lipsyncsrv__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in lipsyncsrv_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LipSyncServiceStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateInference = channel.unary_unary(
                '/lipsyncsrv.LipSyncService/GenerateInference',
                request_serializer=lipsyncsrv__pb2.InferenceRequest.SerializeToString,
                response_deserializer=lipsyncsrv__pb2.InferenceResponse.FromString,
                _registered_method=True)
        self.GenerateBatchInference = channel.unary_unary(
                '/lipsyncsrv.LipSyncService/GenerateBatchInference',
                request_serializer=lipsyncsrv__pb2.BatchInferenceRequest.SerializeToString,
                response_deserializer=lipsyncsrv__pb2.BatchInferenceResponse.FromString,
                _registered_method=True)
        self.StreamInference = channel.stream_stream(
                '/lipsyncsrv.LipSyncService/StreamInference',
                request_serializer=lipsyncsrv__pb2.InferenceRequest.SerializeToString,
                response_deserializer=lipsyncsrv__pb2.InferenceResponse.FromString,
                _registered_method=True)
        self.LoadModel = channel.unary_unary(
                '/lipsyncsrv.LipSyncService/LoadModel',
                request_serializer=lipsyncsrv__pb2.LoadModelRequest.SerializeToString,
                response_deserializer=lipsyncsrv__pb2.LoadModelResponse.FromString,
                _registered_method=True)


class LipSyncServiceServicer(object):
    """Service definition
    """

    def GenerateInference(self, request, context):
        """Single frame inference
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateBatchInference(self, request, context):
        """Batch inference for multiple frames
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamInference(self, request_iterator, context):
        """Streaming inference for real-time applications
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadModel(self, request, context):
        """Model management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LipSyncServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateInference': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateInference,
                    request_deserializer=lipsyncsrv__pb2.InferenceRequest.FromString,
                    response_serializer=lipsyncsrv__pb2.InferenceResponse.SerializeToString,
            ),
            'GenerateBatchInference': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateBatchInference,
                    request_deserializer=lipsyncsrv__pb2.BatchInferenceRequest.FromString,
                    response_serializer=lipsyncsrv__pb2.BatchInferenceResponse.SerializeToString,
            ),
            'StreamInference': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamInference,
                    request_deserializer=lipsyncsrv__pb2.InferenceRequest.FromString,
                    response_serializer=lipsyncsrv__pb2.InferenceResponse.SerializeToString,
            ),
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=lipsyncsrv__pb2.LoadModelRequest.FromString,
                    response_serializer=lipsyncsrv__pb2.LoadModelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lipsyncsrv.LipSyncService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lipsyncsrv.LipSyncService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LipSyncService(object):
    """Service definition
    """

    @staticmethod
    def GenerateInference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lipsyncsrv.LipSyncService/GenerateInference',
            lipsyncsrv__pb2.InferenceRequest.SerializeToString,
            lipsyncsrv__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateBatchInference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lipsyncsrv.LipSyncService/GenerateBatchInference',
            lipsyncsrv__pb2.BatchInferenceRequest.SerializeToString,
            lipsyncsrv__pb2.BatchInferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamInference(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/lipsyncsrv.LipSyncService/StreamInference',
            lipsyncsrv__pb2.InferenceRequest.SerializeToString,
            lipsyncsrv__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lipsyncsrv.LipSyncService/LoadModel',
            lipsyncsrv__pb2.LoadModelRequest.SerializeToString,
            lipsyncsrv__pb2.LoadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
