// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/lipsync.proto

package lipsync

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LipSync_InferBatch_FullMethodName = "/lipsync.LipSync/InferBatch"
	LipSync_Health_FullMethodName     = "/lipsync.LipSync/Health"
)

// LipSyncClient is the client API for LipSync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LipSync service for real-time inference
type LipSyncClient interface {
	// Batch inference: send 1-25 frames at once
	InferBatch(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*BatchResponse, error)
	// Health check
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type lipSyncClient struct {
	cc grpc.ClientConnInterface
}

func NewLipSyncClient(cc grpc.ClientConnInterface) LipSyncClient {
	return &lipSyncClient{cc}
}

func (c *lipSyncClient) InferBatch(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*BatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchResponse)
	err := c.cc.Invoke(ctx, LipSync_InferBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lipSyncClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, LipSync_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LipSyncServer is the server API for LipSync service.
// All implementations must embed UnimplementedLipSyncServer
// for forward compatibility.
//
// LipSync service for real-time inference
type LipSyncServer interface {
	// Batch inference: send 1-25 frames at once
	InferBatch(context.Context, *BatchRequest) (*BatchResponse, error)
	// Health check
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedLipSyncServer()
}

// UnimplementedLipSyncServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLipSyncServer struct{}

func (UnimplementedLipSyncServer) InferBatch(context.Context, *BatchRequest) (*BatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InferBatch not implemented")
}
func (UnimplementedLipSyncServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedLipSyncServer) mustEmbedUnimplementedLipSyncServer() {}
func (UnimplementedLipSyncServer) testEmbeddedByValue()                 {}

// UnsafeLipSyncServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LipSyncServer will
// result in compilation errors.
type UnsafeLipSyncServer interface {
	mustEmbedUnimplementedLipSyncServer()
}

func RegisterLipSyncServer(s grpc.ServiceRegistrar, srv LipSyncServer) {
	// If the following call pancis, it indicates UnimplementedLipSyncServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LipSync_ServiceDesc, srv)
}

func _LipSync_InferBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LipSyncServer).InferBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LipSync_InferBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LipSyncServer).InferBatch(ctx, req.(*BatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LipSync_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LipSyncServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LipSync_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LipSyncServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LipSync_ServiceDesc is the grpc.ServiceDesc for LipSync service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LipSync_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lipsync.LipSync",
	HandlerType: (*LipSyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InferBatch",
			Handler:    _LipSync_InferBatch_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _LipSync_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/lipsync.proto",
}
