// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: optimized_lipsyncsrv.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for optimized inference (uses pre-processed data)
type OptimizedInferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	FrameId       int32                  `protobuf:"varint,2,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"` // No audio_override needed - uses pre-extracted features!
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptimizedInferenceRequest) Reset() {
	*x = OptimizedInferenceRequest{}
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizedInferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizedInferenceRequest) ProtoMessage() {}

func (x *OptimizedInferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizedInferenceRequest.ProtoReflect.Descriptor instead.
func (*OptimizedInferenceRequest) Descriptor() ([]byte, []int) {
	return file_optimized_lipsyncsrv_proto_rawDescGZIP(), []int{0}
}

func (x *OptimizedInferenceRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *OptimizedInferenceRequest) GetFrameId() int32 {
	if x != nil {
		return x.FrameId
	}
	return 0
}

// Response with prediction and metadata
type OptimizedInferenceResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PredictionData   []byte                 `protobuf:"bytes,2,opt,name=prediction_data,json=predictionData,proto3" json:"prediction_data,omitempty"` // JPEG encoded prediction image
	Bounds           []float32              `protobuf:"fixed32,3,rep,packed,name=bounds,proto3" json:"bounds,omitempty"`                              // Bounds array [x1, y1, x2, y2]
	ProcessingTimeMs int32                  `protobuf:"varint,4,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	ModelName        string                 `protobuf:"bytes,5,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	FrameId          int32                  `protobuf:"varint,6,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	PredictionShape  string                 `protobuf:"bytes,7,opt,name=prediction_shape,json=predictionShape,proto3" json:"prediction_shape,omitempty"` // e.g., "320x320x3"
	Error            *string                `protobuf:"bytes,8,opt,name=error,proto3,oneof" json:"error,omitempty"`
	// Performance metadata
	PrepareTimeMs   float64  `protobuf:"fixed64,9,opt,name=prepare_time_ms,json=prepareTimeMs,proto3" json:"prepare_time_ms,omitempty"`
	InferenceTimeMs float64  `protobuf:"fixed64,10,opt,name=inference_time_ms,json=inferenceTimeMs,proto3" json:"inference_time_ms,omitempty"`
	CompositeTimeMs float64  `protobuf:"fixed64,11,opt,name=composite_time_ms,json=compositeTimeMs,proto3" json:"composite_time_ms,omitempty"`
	Optimizations   []string `protobuf:"bytes,12,rep,name=optimizations,proto3" json:"optimizations,omitempty"` // Active optimizations
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OptimizedInferenceResponse) Reset() {
	*x = OptimizedInferenceResponse{}
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizedInferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizedInferenceResponse) ProtoMessage() {}

func (x *OptimizedInferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizedInferenceResponse.ProtoReflect.Descriptor instead.
func (*OptimizedInferenceResponse) Descriptor() ([]byte, []int) {
	return file_optimized_lipsyncsrv_proto_rawDescGZIP(), []int{1}
}

func (x *OptimizedInferenceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OptimizedInferenceResponse) GetPredictionData() []byte {
	if x != nil {
		return x.PredictionData
	}
	return nil
}

func (x *OptimizedInferenceResponse) GetBounds() []float32 {
	if x != nil {
		return x.Bounds
	}
	return nil
}

func (x *OptimizedInferenceResponse) GetProcessingTimeMs() int32 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

func (x *OptimizedInferenceResponse) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *OptimizedInferenceResponse) GetFrameId() int32 {
	if x != nil {
		return x.FrameId
	}
	return 0
}

func (x *OptimizedInferenceResponse) GetPredictionShape() string {
	if x != nil {
		return x.PredictionShape
	}
	return ""
}

func (x *OptimizedInferenceResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *OptimizedInferenceResponse) GetPrepareTimeMs() float64 {
	if x != nil {
		return x.PrepareTimeMs
	}
	return 0
}

func (x *OptimizedInferenceResponse) GetInferenceTimeMs() float64 {
	if x != nil {
		return x.InferenceTimeMs
	}
	return 0
}

func (x *OptimizedInferenceResponse) GetCompositeTimeMs() float64 {
	if x != nil {
		return x.CompositeTimeMs
	}
	return 0
}

func (x *OptimizedInferenceResponse) GetOptimizations() []string {
	if x != nil {
		return x.Optimizations
	}
	return nil
}

// Batch request for multiple frames
type BatchInferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	FrameIds      []int32                `protobuf:"varint,2,rep,packed,name=frame_ids,json=frameIds,proto3" json:"frame_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchInferenceRequest) Reset() {
	*x = BatchInferenceRequest{}
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchInferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchInferenceRequest) ProtoMessage() {}

func (x *BatchInferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchInferenceRequest.ProtoReflect.Descriptor instead.
func (*BatchInferenceRequest) Descriptor() ([]byte, []int) {
	return file_optimized_lipsyncsrv_proto_rawDescGZIP(), []int{2}
}

func (x *BatchInferenceRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *BatchInferenceRequest) GetFrameIds() []int32 {
	if x != nil {
		return x.FrameIds
	}
	return nil
}

// Optimized batch request with audio chunks (avoids redundant audio data)
type BatchInferenceWithAudioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	StartFrameId  int32                  `protobuf:"varint,2,opt,name=start_frame_id,json=startFrameId,proto3" json:"start_frame_id,omitempty"` // First frame to generate
	FrameCount    int32                  `protobuf:"varint,3,opt,name=frame_count,json=frameCount,proto3" json:"frame_count,omitempty"`         // Number of consecutive frames
	AudioChunks   [][]byte               `protobuf:"bytes,4,rep,name=audio_chunks,json=audioChunks,proto3" json:"audio_chunks,omitempty"`       // Audio chunks (40ms each)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchInferenceWithAudioRequest) Reset() {
	*x = BatchInferenceWithAudioRequest{}
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchInferenceWithAudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchInferenceWithAudioRequest) ProtoMessage() {}

func (x *BatchInferenceWithAudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchInferenceWithAudioRequest.ProtoReflect.Descriptor instead.
func (*BatchInferenceWithAudioRequest) Descriptor() ([]byte, []int) {
	return file_optimized_lipsyncsrv_proto_rawDescGZIP(), []int{3}
}

func (x *BatchInferenceWithAudioRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *BatchInferenceWithAudioRequest) GetStartFrameId() int32 {
	if x != nil {
		return x.StartFrameId
	}
	return 0
}

func (x *BatchInferenceWithAudioRequest) GetFrameCount() int32 {
	if x != nil {
		return x.FrameCount
	}
	return 0
}

func (x *BatchInferenceWithAudioRequest) GetAudioChunks() [][]byte {
	if x != nil {
		return x.AudioChunks
	}
	return nil
}

// Batch response
type BatchInferenceResponse struct {
	state                 protoimpl.MessageState        `protogen:"open.v1"`
	Responses             []*OptimizedInferenceResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	TotalProcessingTimeMs int32                         `protobuf:"varint,2,opt,name=total_processing_time_ms,json=totalProcessingTimeMs,proto3" json:"total_processing_time_ms,omitempty"`
	AvgFrameTimeMs        float64                       `protobuf:"fixed64,3,opt,name=avg_frame_time_ms,json=avgFrameTimeMs,proto3" json:"avg_frame_time_ms,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *BatchInferenceResponse) Reset() {
	*x = BatchInferenceResponse{}
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchInferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchInferenceResponse) ProtoMessage() {}

func (x *BatchInferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchInferenceResponse.ProtoReflect.Descriptor instead.
func (*BatchInferenceResponse) Descriptor() ([]byte, []int) {
	return file_optimized_lipsyncsrv_proto_rawDescGZIP(), []int{4}
}

func (x *BatchInferenceResponse) GetResponses() []*OptimizedInferenceResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *BatchInferenceResponse) GetTotalProcessingTimeMs() int32 {
	if x != nil {
		return x.TotalProcessingTimeMs
	}
	return 0
}

func (x *BatchInferenceResponse) GetAvgFrameTimeMs() float64 {
	if x != nil {
		return x.AvgFrameTimeMs
	}
	return 0
}

// Model package loading request
type LoadPackageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageName   string                 `protobuf:"bytes,1,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	PackageDir    string                 `protobuf:"bytes,2,opt,name=package_dir,json=packageDir,proto3" json:"package_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadPackageRequest) Reset() {
	*x = LoadPackageRequest{}
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadPackageRequest) ProtoMessage() {}

func (x *LoadPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadPackageRequest.ProtoReflect.Descriptor instead.
func (*LoadPackageRequest) Descriptor() ([]byte, []int) {
	return file_optimized_lipsyncsrv_proto_rawDescGZIP(), []int{5}
}

func (x *LoadPackageRequest) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *LoadPackageRequest) GetPackageDir() string {
	if x != nil {
		return x.PackageDir
	}
	return ""
}

// Model package loading response
type LoadPackageResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Success              bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PackageName          string                 `protobuf:"bytes,2,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	Message              string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	InitializationTimeMs int32                  `protobuf:"varint,4,opt,name=initialization_time_ms,json=initializationTimeMs,proto3" json:"initialization_time_ms,omitempty"`
	FrameCount           int32                  `protobuf:"varint,5,opt,name=frame_count,json=frameCount,proto3" json:"frame_count,omitempty"`
	Device               string                 `protobuf:"bytes,6,opt,name=device,proto3" json:"device,omitempty"`
	VideosLoaded         []string               `protobuf:"bytes,7,rep,name=videos_loaded,json=videosLoaded,proto3" json:"videos_loaded,omitempty"`
	AudioFeaturesShape   []int32                `protobuf:"varint,8,rep,packed,name=audio_features_shape,json=audioFeaturesShape,proto3" json:"audio_features_shape,omitempty"`
	MemoryMappedAudio    bool                   `protobuf:"varint,9,opt,name=memory_mapped_audio,json=memoryMappedAudio,proto3" json:"memory_mapped_audio,omitempty"`
	Error                *string                `protobuf:"bytes,10,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *LoadPackageResponse) Reset() {
	*x = LoadPackageResponse{}
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadPackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadPackageResponse) ProtoMessage() {}

func (x *LoadPackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadPackageResponse.ProtoReflect.Descriptor instead.
func (*LoadPackageResponse) Descriptor() ([]byte, []int) {
	return file_optimized_lipsyncsrv_proto_rawDescGZIP(), []int{6}
}

func (x *LoadPackageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoadPackageResponse) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *LoadPackageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoadPackageResponse) GetInitializationTimeMs() int32 {
	if x != nil {
		return x.InitializationTimeMs
	}
	return 0
}

func (x *LoadPackageResponse) GetFrameCount() int32 {
	if x != nil {
		return x.FrameCount
	}
	return 0
}

func (x *LoadPackageResponse) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *LoadPackageResponse) GetVideosLoaded() []string {
	if x != nil {
		return x.VideosLoaded
	}
	return nil
}

func (x *LoadPackageResponse) GetAudioFeaturesShape() []int32 {
	if x != nil {
		return x.AudioFeaturesShape
	}
	return nil
}

func (x *LoadPackageResponse) GetMemoryMappedAudio() bool {
	if x != nil {
		return x.MemoryMappedAudio
	}
	return false
}

func (x *LoadPackageResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// Stats request
type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_optimized_lipsyncsrv_proto_rawDescGZIP(), []int{7}
}

func (x *StatsRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

// Stats response
type StatsResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ModelName           string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	TotalRequests       int32                  `protobuf:"varint,2,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	AvgInferenceTimeMs  float64                `protobuf:"fixed64,3,opt,name=avg_inference_time_ms,json=avgInferenceTimeMs,proto3" json:"avg_inference_time_ms,omitempty"`
	MinInferenceTimeMs  float64                `protobuf:"fixed64,4,opt,name=min_inference_time_ms,json=minInferenceTimeMs,proto3" json:"min_inference_time_ms,omitempty"`
	MaxInferenceTimeMs  float64                `protobuf:"fixed64,5,opt,name=max_inference_time_ms,json=maxInferenceTimeMs,proto3" json:"max_inference_time_ms,omitempty"`
	FrameCount          int32                  `protobuf:"varint,6,opt,name=frame_count,json=frameCount,proto3" json:"frame_count,omitempty"`
	Device              string                 `protobuf:"bytes,7,opt,name=device,proto3" json:"device,omitempty"`
	OptimizationsActive []string               `protobuf:"bytes,8,rep,name=optimizations_active,json=optimizationsActive,proto3" json:"optimizations_active,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_optimized_lipsyncsrv_proto_rawDescGZIP(), []int{8}
}

func (x *StatsResponse) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *StatsResponse) GetTotalRequests() int32 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *StatsResponse) GetAvgInferenceTimeMs() float64 {
	if x != nil {
		return x.AvgInferenceTimeMs
	}
	return 0
}

func (x *StatsResponse) GetMinInferenceTimeMs() float64 {
	if x != nil {
		return x.MinInferenceTimeMs
	}
	return 0
}

func (x *StatsResponse) GetMaxInferenceTimeMs() float64 {
	if x != nil {
		return x.MaxInferenceTimeMs
	}
	return 0
}

func (x *StatsResponse) GetFrameCount() int32 {
	if x != nil {
		return x.FrameCount
	}
	return 0
}

func (x *StatsResponse) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *StatsResponse) GetOptimizationsActive() []string {
	if x != nil {
		return x.OptimizationsActive
	}
	return nil
}

// List models request
type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_optimized_lipsyncsrv_proto_rawDescGZIP(), []int{9}
}

// List models response
type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoadedModels  []string               `protobuf:"bytes,1,rep,name=loaded_models,json=loadedModels,proto3" json:"loaded_models,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_optimized_lipsyncsrv_proto_rawDescGZIP(), []int{10}
}

func (x *ListModelsResponse) GetLoadedModels() []string {
	if x != nil {
		return x.LoadedModels
	}
	return nil
}

func (x *ListModelsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Health check request
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_optimized_lipsyncsrv_proto_rawDescGZIP(), []int{11}
}

// Health check response
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	LoadedModels  int32                  `protobuf:"varint,3,opt,name=loaded_models,json=loadedModels,proto3" json:"loaded_models,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_optimized_lipsyncsrv_proto_rawDescGZIP(), []int{12}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetLoadedModels() int32 {
	if x != nil {
		return x.LoadedModels
	}
	return 0
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

// Get video frame request
type GetVideoFrameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	FrameId       int32                  `protobuf:"varint,2,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	VideoType     string                 `protobuf:"bytes,3,opt,name=video_type,json=videoType,proto3" json:"video_type,omitempty"` // "full_body", "face_regions", "masked_regions"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoFrameRequest) Reset() {
	*x = GetVideoFrameRequest{}
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoFrameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoFrameRequest) ProtoMessage() {}

func (x *GetVideoFrameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoFrameRequest.ProtoReflect.Descriptor instead.
func (*GetVideoFrameRequest) Descriptor() ([]byte, []int) {
	return file_optimized_lipsyncsrv_proto_rawDescGZIP(), []int{13}
}

func (x *GetVideoFrameRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *GetVideoFrameRequest) GetFrameId() int32 {
	if x != nil {
		return x.FrameId
	}
	return 0
}

func (x *GetVideoFrameRequest) GetVideoType() string {
	if x != nil {
		return x.VideoType
	}
	return ""
}

// Get video frame response
type GetVideoFrameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	FrameData     []byte                 `protobuf:"bytes,2,opt,name=frame_data,json=frameData,proto3" json:"frame_data,omitempty"` // JPEG encoded original video frame
	FrameId       int32                  `protobuf:"varint,3,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	VideoType     string                 `protobuf:"bytes,4,opt,name=video_type,json=videoType,proto3" json:"video_type,omitempty"`
	Error         *string                `protobuf:"bytes,5,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoFrameResponse) Reset() {
	*x = GetVideoFrameResponse{}
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoFrameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoFrameResponse) ProtoMessage() {}

func (x *GetVideoFrameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoFrameResponse.ProtoReflect.Descriptor instead.
func (*GetVideoFrameResponse) Descriptor() ([]byte, []int) {
	return file_optimized_lipsyncsrv_proto_rawDescGZIP(), []int{14}
}

func (x *GetVideoFrameResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetVideoFrameResponse) GetFrameData() []byte {
	if x != nil {
		return x.FrameData
	}
	return nil
}

func (x *GetVideoFrameResponse) GetFrameId() int32 {
	if x != nil {
		return x.FrameId
	}
	return 0
}

func (x *GetVideoFrameResponse) GetVideoType() string {
	if x != nil {
		return x.VideoType
	}
	return ""
}

func (x *GetVideoFrameResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// Get model metadata request
type GetModelMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelMetadataRequest) Reset() {
	*x = GetModelMetadataRequest{}
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelMetadataRequest) ProtoMessage() {}

func (x *GetModelMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetModelMetadataRequest) Descriptor() ([]byte, []int) {
	return file_optimized_lipsyncsrv_proto_rawDescGZIP(), []int{15}
}

func (x *GetModelMetadataRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

// Get model metadata response
type GetModelMetadataResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ModelName       string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	FrameCount      int32                  `protobuf:"varint,3,opt,name=frame_count,json=frameCount,proto3" json:"frame_count,omitempty"`
	AvailableVideos []string               `protobuf:"bytes,4,rep,name=available_videos,json=availableVideos,proto3" json:"available_videos,omitempty"` // ["full_body", "face_regions", "masked_regions"]
	AudioPath       string                 `protobuf:"bytes,5,opt,name=audio_path,json=audioPath,proto3" json:"audio_path,omitempty"`                   // Relative path to audio file
	Bounds          []float32              `protobuf:"fixed32,6,rep,packed,name=bounds,proto3" json:"bounds,omitempty"`                                 // Default face bounds [x1, y1, x2, y2]
	Error           *string                `protobuf:"bytes,7,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetModelMetadataResponse) Reset() {
	*x = GetModelMetadataResponse{}
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelMetadataResponse) ProtoMessage() {}

func (x *GetModelMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_optimized_lipsyncsrv_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetModelMetadataResponse) Descriptor() ([]byte, []int) {
	return file_optimized_lipsyncsrv_proto_rawDescGZIP(), []int{16}
}

func (x *GetModelMetadataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetModelMetadataResponse) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *GetModelMetadataResponse) GetFrameCount() int32 {
	if x != nil {
		return x.FrameCount
	}
	return 0
}

func (x *GetModelMetadataResponse) GetAvailableVideos() []string {
	if x != nil {
		return x.AvailableVideos
	}
	return nil
}

func (x *GetModelMetadataResponse) GetAudioPath() string {
	if x != nil {
		return x.AudioPath
	}
	return ""
}

func (x *GetModelMetadataResponse) GetBounds() []float32 {
	if x != nil {
		return x.Bounds
	}
	return nil
}

func (x *GetModelMetadataResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_optimized_lipsyncsrv_proto protoreflect.FileDescriptor

const file_optimized_lipsyncsrv_proto_rawDesc = "" +
	"\n" +
	"\x1aoptimized_lipsyncsrv.proto\x12\x14optimized_lipsyncsrv\"U\n" +
	"\x19OptimizedInferenceRequest\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12\x19\n" +
	"\bframe_id\x18\x02 \x01(\x05R\aframeId\"\xd5\x03\n" +
	"\x1aOptimizedInferenceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fprediction_data\x18\x02 \x01(\fR\x0epredictionData\x12\x16\n" +
	"\x06bounds\x18\x03 \x03(\x02R\x06bounds\x12,\n" +
	"\x12processing_time_ms\x18\x04 \x01(\x05R\x10processingTimeMs\x12\x1d\n" +
	"\n" +
	"model_name\x18\x05 \x01(\tR\tmodelName\x12\x19\n" +
	"\bframe_id\x18\x06 \x01(\x05R\aframeId\x12)\n" +
	"\x10prediction_shape\x18\a \x01(\tR\x0fpredictionShape\x12\x19\n" +
	"\x05error\x18\b \x01(\tH\x00R\x05error\x88\x01\x01\x12&\n" +
	"\x0fprepare_time_ms\x18\t \x01(\x01R\rprepareTimeMs\x12*\n" +
	"\x11inference_time_ms\x18\n" +
	" \x01(\x01R\x0finferenceTimeMs\x12*\n" +
	"\x11composite_time_ms\x18\v \x01(\x01R\x0fcompositeTimeMs\x12$\n" +
	"\roptimizations\x18\f \x03(\tR\roptimizationsB\b\n" +
	"\x06_error\"S\n" +
	"\x15BatchInferenceRequest\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12\x1b\n" +
	"\tframe_ids\x18\x02 \x03(\x05R\bframeIds\"\xa9\x01\n" +
	"\x1eBatchInferenceWithAudioRequest\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12$\n" +
	"\x0estart_frame_id\x18\x02 \x01(\x05R\fstartFrameId\x12\x1f\n" +
	"\vframe_count\x18\x03 \x01(\x05R\n" +
	"frameCount\x12!\n" +
	"\faudio_chunks\x18\x04 \x03(\fR\vaudioChunks\"\xcc\x01\n" +
	"\x16BatchInferenceResponse\x12N\n" +
	"\tresponses\x18\x01 \x03(\v20.optimized_lipsyncsrv.OptimizedInferenceResponseR\tresponses\x127\n" +
	"\x18total_processing_time_ms\x18\x02 \x01(\x05R\x15totalProcessingTimeMs\x12)\n" +
	"\x11avg_frame_time_ms\x18\x03 \x01(\x01R\x0eavgFrameTimeMs\"X\n" +
	"\x12LoadPackageRequest\x12!\n" +
	"\fpackage_name\x18\x01 \x01(\tR\vpackageName\x12\x1f\n" +
	"\vpackage_dir\x18\x02 \x01(\tR\n" +
	"packageDir\"\x87\x03\n" +
	"\x13LoadPackageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fpackage_name\x18\x02 \x01(\tR\vpackageName\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x124\n" +
	"\x16initialization_time_ms\x18\x04 \x01(\x05R\x14initializationTimeMs\x12\x1f\n" +
	"\vframe_count\x18\x05 \x01(\x05R\n" +
	"frameCount\x12\x16\n" +
	"\x06device\x18\x06 \x01(\tR\x06device\x12#\n" +
	"\rvideos_loaded\x18\a \x03(\tR\fvideosLoaded\x120\n" +
	"\x14audio_features_shape\x18\b \x03(\x05R\x12audioFeaturesShape\x12.\n" +
	"\x13memory_mapped_audio\x18\t \x01(\bR\x11memoryMappedAudio\x12\x19\n" +
	"\x05error\x18\n" +
	" \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"-\n" +
	"\fStatsRequest\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\"\xda\x02\n" +
	"\rStatsResponse\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12%\n" +
	"\x0etotal_requests\x18\x02 \x01(\x05R\rtotalRequests\x121\n" +
	"\x15avg_inference_time_ms\x18\x03 \x01(\x01R\x12avgInferenceTimeMs\x121\n" +
	"\x15min_inference_time_ms\x18\x04 \x01(\x01R\x12minInferenceTimeMs\x121\n" +
	"\x15max_inference_time_ms\x18\x05 \x01(\x01R\x12maxInferenceTimeMs\x12\x1f\n" +
	"\vframe_count\x18\x06 \x01(\x05R\n" +
	"frameCount\x12\x16\n" +
	"\x06device\x18\a \x01(\tR\x06device\x121\n" +
	"\x14optimizations_active\x18\b \x03(\tR\x13optimizationsActive\"\x13\n" +
	"\x11ListModelsRequest\"O\n" +
	"\x12ListModelsResponse\x12#\n" +
	"\rloaded_models\x18\x01 \x03(\tR\floadedModels\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\x0f\n" +
	"\rHealthRequest\"\x8e\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rloaded_models\x18\x03 \x01(\x05R\floadedModels\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\"o\n" +
	"\x14GetVideoFrameRequest\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12\x19\n" +
	"\bframe_id\x18\x02 \x01(\x05R\aframeId\x12\x1d\n" +
	"\n" +
	"video_type\x18\x03 \x01(\tR\tvideoType\"\xaf\x01\n" +
	"\x15GetVideoFrameResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"frame_data\x18\x02 \x01(\fR\tframeData\x12\x19\n" +
	"\bframe_id\x18\x03 \x01(\x05R\aframeId\x12\x1d\n" +
	"\n" +
	"video_type\x18\x04 \x01(\tR\tvideoType\x12\x19\n" +
	"\x05error\x18\x05 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"8\n" +
	"\x17GetModelMetadataRequest\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\"\xfb\x01\n" +
	"\x18GetModelMetadataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12\x1f\n" +
	"\vframe_count\x18\x03 \x01(\x05R\n" +
	"frameCount\x12)\n" +
	"\x10available_videos\x18\x04 \x03(\tR\x0favailableVideos\x12\x1d\n" +
	"\n" +
	"audio_path\x18\x05 \x01(\tR\taudioPath\x12\x16\n" +
	"\x06bounds\x18\x06 \x03(\x02R\x06bounds\x12\x19\n" +
	"\x05error\x18\a \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error2\xcf\b\n" +
	"\x17OptimizedLipSyncService\x12v\n" +
	"\x11GenerateInference\x12/.optimized_lipsyncsrv.OptimizedInferenceRequest\x1a0.optimized_lipsyncsrv.OptimizedInferenceResponse\x12s\n" +
	"\x16GenerateBatchInference\x12+.optimized_lipsyncsrv.BatchInferenceRequest\x1a,.optimized_lipsyncsrv.BatchInferenceResponse\x12|\n" +
	"\x16GenerateBatchWithAudio\x124.optimized_lipsyncsrv.BatchInferenceWithAudioRequest\x1a,.optimized_lipsyncsrv.BatchInferenceResponse\x12x\n" +
	"\x0fStreamInference\x12/.optimized_lipsyncsrv.OptimizedInferenceRequest\x1a0.optimized_lipsyncsrv.OptimizedInferenceResponse(\x010\x01\x12b\n" +
	"\vLoadPackage\x12(.optimized_lipsyncsrv.LoadPackageRequest\x1a).optimized_lipsyncsrv.LoadPackageResponse\x12S\n" +
	"\bGetStats\x12\".optimized_lipsyncsrv.StatsRequest\x1a#.optimized_lipsyncsrv.StatsResponse\x12_\n" +
	"\n" +
	"ListModels\x12'.optimized_lipsyncsrv.ListModelsRequest\x1a(.optimized_lipsyncsrv.ListModelsResponse\x12X\n" +
	"\vHealthCheck\x12#.optimized_lipsyncsrv.HealthRequest\x1a$.optimized_lipsyncsrv.HealthResponse\x12h\n" +
	"\rGetVideoFrame\x12*.optimized_lipsyncsrv.GetVideoFrameRequest\x1a+.optimized_lipsyncsrv.GetVideoFrameResponse\x12q\n" +
	"\x10GetModelMetadata\x12-.optimized_lipsyncsrv.GetModelMetadataRequest\x1a..optimized_lipsyncsrv.GetModelMetadataResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_optimized_lipsyncsrv_proto_rawDescOnce sync.Once
	file_optimized_lipsyncsrv_proto_rawDescData []byte
)

func file_optimized_lipsyncsrv_proto_rawDescGZIP() []byte {
	file_optimized_lipsyncsrv_proto_rawDescOnce.Do(func() {
		file_optimized_lipsyncsrv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_optimized_lipsyncsrv_proto_rawDesc), len(file_optimized_lipsyncsrv_proto_rawDesc)))
	})
	return file_optimized_lipsyncsrv_proto_rawDescData
}

var file_optimized_lipsyncsrv_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_optimized_lipsyncsrv_proto_goTypes = []any{
	(*OptimizedInferenceRequest)(nil),      // 0: optimized_lipsyncsrv.OptimizedInferenceRequest
	(*OptimizedInferenceResponse)(nil),     // 1: optimized_lipsyncsrv.OptimizedInferenceResponse
	(*BatchInferenceRequest)(nil),          // 2: optimized_lipsyncsrv.BatchInferenceRequest
	(*BatchInferenceWithAudioRequest)(nil), // 3: optimized_lipsyncsrv.BatchInferenceWithAudioRequest
	(*BatchInferenceResponse)(nil),         // 4: optimized_lipsyncsrv.BatchInferenceResponse
	(*LoadPackageRequest)(nil),             // 5: optimized_lipsyncsrv.LoadPackageRequest
	(*LoadPackageResponse)(nil),            // 6: optimized_lipsyncsrv.LoadPackageResponse
	(*StatsRequest)(nil),                   // 7: optimized_lipsyncsrv.StatsRequest
	(*StatsResponse)(nil),                  // 8: optimized_lipsyncsrv.StatsResponse
	(*ListModelsRequest)(nil),              // 9: optimized_lipsyncsrv.ListModelsRequest
	(*ListModelsResponse)(nil),             // 10: optimized_lipsyncsrv.ListModelsResponse
	(*HealthRequest)(nil),                  // 11: optimized_lipsyncsrv.HealthRequest
	(*HealthResponse)(nil),                 // 12: optimized_lipsyncsrv.HealthResponse
	(*GetVideoFrameRequest)(nil),           // 13: optimized_lipsyncsrv.GetVideoFrameRequest
	(*GetVideoFrameResponse)(nil),          // 14: optimized_lipsyncsrv.GetVideoFrameResponse
	(*GetModelMetadataRequest)(nil),        // 15: optimized_lipsyncsrv.GetModelMetadataRequest
	(*GetModelMetadataResponse)(nil),       // 16: optimized_lipsyncsrv.GetModelMetadataResponse
}
var file_optimized_lipsyncsrv_proto_depIdxs = []int32{
	1,  // 0: optimized_lipsyncsrv.BatchInferenceResponse.responses:type_name -> optimized_lipsyncsrv.OptimizedInferenceResponse
	0,  // 1: optimized_lipsyncsrv.OptimizedLipSyncService.GenerateInference:input_type -> optimized_lipsyncsrv.OptimizedInferenceRequest
	2,  // 2: optimized_lipsyncsrv.OptimizedLipSyncService.GenerateBatchInference:input_type -> optimized_lipsyncsrv.BatchInferenceRequest
	3,  // 3: optimized_lipsyncsrv.OptimizedLipSyncService.GenerateBatchWithAudio:input_type -> optimized_lipsyncsrv.BatchInferenceWithAudioRequest
	0,  // 4: optimized_lipsyncsrv.OptimizedLipSyncService.StreamInference:input_type -> optimized_lipsyncsrv.OptimizedInferenceRequest
	5,  // 5: optimized_lipsyncsrv.OptimizedLipSyncService.LoadPackage:input_type -> optimized_lipsyncsrv.LoadPackageRequest
	7,  // 6: optimized_lipsyncsrv.OptimizedLipSyncService.GetStats:input_type -> optimized_lipsyncsrv.StatsRequest
	9,  // 7: optimized_lipsyncsrv.OptimizedLipSyncService.ListModels:input_type -> optimized_lipsyncsrv.ListModelsRequest
	11, // 8: optimized_lipsyncsrv.OptimizedLipSyncService.HealthCheck:input_type -> optimized_lipsyncsrv.HealthRequest
	13, // 9: optimized_lipsyncsrv.OptimizedLipSyncService.GetVideoFrame:input_type -> optimized_lipsyncsrv.GetVideoFrameRequest
	15, // 10: optimized_lipsyncsrv.OptimizedLipSyncService.GetModelMetadata:input_type -> optimized_lipsyncsrv.GetModelMetadataRequest
	1,  // 11: optimized_lipsyncsrv.OptimizedLipSyncService.GenerateInference:output_type -> optimized_lipsyncsrv.OptimizedInferenceResponse
	4,  // 12: optimized_lipsyncsrv.OptimizedLipSyncService.GenerateBatchInference:output_type -> optimized_lipsyncsrv.BatchInferenceResponse
	4,  // 13: optimized_lipsyncsrv.OptimizedLipSyncService.GenerateBatchWithAudio:output_type -> optimized_lipsyncsrv.BatchInferenceResponse
	1,  // 14: optimized_lipsyncsrv.OptimizedLipSyncService.StreamInference:output_type -> optimized_lipsyncsrv.OptimizedInferenceResponse
	6,  // 15: optimized_lipsyncsrv.OptimizedLipSyncService.LoadPackage:output_type -> optimized_lipsyncsrv.LoadPackageResponse
	8,  // 16: optimized_lipsyncsrv.OptimizedLipSyncService.GetStats:output_type -> optimized_lipsyncsrv.StatsResponse
	10, // 17: optimized_lipsyncsrv.OptimizedLipSyncService.ListModels:output_type -> optimized_lipsyncsrv.ListModelsResponse
	12, // 18: optimized_lipsyncsrv.OptimizedLipSyncService.HealthCheck:output_type -> optimized_lipsyncsrv.HealthResponse
	14, // 19: optimized_lipsyncsrv.OptimizedLipSyncService.GetVideoFrame:output_type -> optimized_lipsyncsrv.GetVideoFrameResponse
	16, // 20: optimized_lipsyncsrv.OptimizedLipSyncService.GetModelMetadata:output_type -> optimized_lipsyncsrv.GetModelMetadataResponse
	11, // [11:21] is the sub-list for method output_type
	1,  // [1:11] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_optimized_lipsyncsrv_proto_init() }
func file_optimized_lipsyncsrv_proto_init() {
	if File_optimized_lipsyncsrv_proto != nil {
		return
	}
	file_optimized_lipsyncsrv_proto_msgTypes[1].OneofWrappers = []any{}
	file_optimized_lipsyncsrv_proto_msgTypes[6].OneofWrappers = []any{}
	file_optimized_lipsyncsrv_proto_msgTypes[14].OneofWrappers = []any{}
	file_optimized_lipsyncsrv_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_optimized_lipsyncsrv_proto_rawDesc), len(file_optimized_lipsyncsrv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_optimized_lipsyncsrv_proto_goTypes,
		DependencyIndexes: file_optimized_lipsyncsrv_proto_depIdxs,
		MessageInfos:      file_optimized_lipsyncsrv_proto_msgTypes,
	}.Build()
	File_optimized_lipsyncsrv_proto = out.File
	file_optimized_lipsyncsrv_proto_goTypes = nil
	file_optimized_lipsyncsrv_proto_depIdxs = nil
}
