// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/multitenant.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompositeBatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Model identifier (e.g., "sanders", "bob", "jane")
	// Server will auto-load if not already in memory
	ModelId string `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	// Visual frames: flattened array [batch_size * 6 * 320 * 320]
	VisualFrames []float32 `protobuf:"fixed32,2,rep,packed,name=visual_frames,json=visualFrames,proto3" json:"visual_frames,omitempty"`
	// Audio features: single window [32 * 16 * 16]
	AudioFeatures []float32 `protobuf:"fixed32,3,rep,packed,name=audio_features,json=audioFeatures,proto3" json:"audio_features,omitempty"`
	// Number of frames in this batch (1-25)
	BatchSize int32 `protobuf:"varint,4,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	// Starting frame index for crop rectangle and background lookup
	StartFrameIdx int32 `protobuf:"varint,5,opt,name=start_frame_idx,json=startFrameIdx,proto3" json:"start_frame_idx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompositeBatchRequest) Reset() {
	*x = CompositeBatchRequest{}
	mi := &file_proto_multitenant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompositeBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompositeBatchRequest) ProtoMessage() {}

func (x *CompositeBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_multitenant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompositeBatchRequest.ProtoReflect.Descriptor instead.
func (*CompositeBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_multitenant_proto_rawDescGZIP(), []int{0}
}

func (x *CompositeBatchRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *CompositeBatchRequest) GetVisualFrames() []float32 {
	if x != nil {
		return x.VisualFrames
	}
	return nil
}

func (x *CompositeBatchRequest) GetAudioFeatures() []float32 {
	if x != nil {
		return x.AudioFeatures
	}
	return nil
}

func (x *CompositeBatchRequest) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *CompositeBatchRequest) GetStartFrameIdx() int32 {
	if x != nil {
		return x.StartFrameIdx
	}
	return 0
}

type CompositeBatchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Composited frames: PNG-encoded bytes for each frame
	CompositedFrames [][]byte `protobuf:"bytes,1,rep,name=composited_frames,json=compositedFrames,proto3" json:"composited_frames,omitempty"`
	// Timing information
	InferenceTimeMs float64 `protobuf:"fixed64,2,opt,name=inference_time_ms,json=inferenceTimeMs,proto3" json:"inference_time_ms,omitempty"`
	CompositeTimeMs float64 `protobuf:"fixed64,3,opt,name=composite_time_ms,json=compositeTimeMs,proto3" json:"composite_time_ms,omitempty"`
	TotalTimeMs     float64 `protobuf:"fixed64,4,opt,name=total_time_ms,json=totalTimeMs,proto3" json:"total_time_ms,omitempty"`
	// Model was loaded during this request
	ModelLoaded     bool    `protobuf:"varint,5,opt,name=model_loaded,json=modelLoaded,proto3" json:"model_loaded,omitempty"`
	ModelLoadTimeMs float64 `protobuf:"fixed64,6,opt,name=model_load_time_ms,json=modelLoadTimeMs,proto3" json:"model_load_time_ms,omitempty"`
	// Success/error
	Success       bool   `protobuf:"varint,7,opt,name=success,proto3" json:"success,omitempty"`
	Error         string `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompositeBatchResponse) Reset() {
	*x = CompositeBatchResponse{}
	mi := &file_proto_multitenant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompositeBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompositeBatchResponse) ProtoMessage() {}

func (x *CompositeBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_multitenant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompositeBatchResponse.ProtoReflect.Descriptor instead.
func (*CompositeBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_multitenant_proto_rawDescGZIP(), []int{1}
}

func (x *CompositeBatchResponse) GetCompositedFrames() [][]byte {
	if x != nil {
		return x.CompositedFrames
	}
	return nil
}

func (x *CompositeBatchResponse) GetInferenceTimeMs() float64 {
	if x != nil {
		return x.InferenceTimeMs
	}
	return 0
}

func (x *CompositeBatchResponse) GetCompositeTimeMs() float64 {
	if x != nil {
		return x.CompositeTimeMs
	}
	return 0
}

func (x *CompositeBatchResponse) GetTotalTimeMs() float64 {
	if x != nil {
		return x.TotalTimeMs
	}
	return 0
}

func (x *CompositeBatchResponse) GetModelLoaded() bool {
	if x != nil {
		return x.ModelLoaded
	}
	return false
}

func (x *CompositeBatchResponse) GetModelLoadTimeMs() float64 {
	if x != nil {
		return x.ModelLoadTimeMs
	}
	return 0
}

func (x *CompositeBatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CompositeBatchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_proto_multitenant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_multitenant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_proto_multitenant_proto_rawDescGZIP(), []int{2}
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*ModelInfo           `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_proto_multitenant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_multitenant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_proto_multitenant_proto_rawDescGZIP(), []int{3}
}

func (x *ListModelsResponse) GetModels() []*ModelInfo {
	if x != nil {
		return x.Models
	}
	return nil
}

type ModelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Loaded        bool                   `protobuf:"varint,2,opt,name=loaded,proto3" json:"loaded,omitempty"` // Currently loaded in memory
	ModelPath     string                 `protobuf:"bytes,3,opt,name=model_path,json=modelPath,proto3" json:"model_path,omitempty"`
	BackgroundDir string                 `protobuf:"bytes,4,opt,name=background_dir,json=backgroundDir,proto3" json:"background_dir,omitempty"`
	CropRectsPath string                 `protobuf:"bytes,5,opt,name=crop_rects_path,json=cropRectsPath,proto3" json:"crop_rects_path,omitempty"`
	// Usage statistics (if loaded)
	Stats         *ModelStats `protobuf:"bytes,6,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_proto_multitenant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_multitenant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_proto_multitenant_proto_rawDescGZIP(), []int{4}
}

func (x *ModelInfo) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ModelInfo) GetLoaded() bool {
	if x != nil {
		return x.Loaded
	}
	return false
}

func (x *ModelInfo) GetModelPath() string {
	if x != nil {
		return x.ModelPath
	}
	return ""
}

func (x *ModelInfo) GetBackgroundDir() string {
	if x != nil {
		return x.BackgroundDir
	}
	return ""
}

func (x *ModelInfo) GetCropRectsPath() string {
	if x != nil {
		return x.CropRectsPath
	}
	return ""
}

func (x *ModelInfo) GetStats() *ModelStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type ModelStats struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UsageCount           int64                  `protobuf:"varint,1,opt,name=usage_count,json=usageCount,proto3" json:"usage_count,omitempty"`                                    // Total number of inferences
	LastUsedUnixMs       int64                  `protobuf:"varint,2,opt,name=last_used_unix_ms,json=lastUsedUnixMs,proto3" json:"last_used_unix_ms,omitempty"`                    // Last access time (Unix milliseconds)
	TotalInferenceTimeMs float64                `protobuf:"fixed64,3,opt,name=total_inference_time_ms,json=totalInferenceTimeMs,proto3" json:"total_inference_time_ms,omitempty"` // Cumulative inference time
	MemoryBytes          int64                  `protobuf:"varint,4,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`                                 // Estimated memory usage
	LoadedUnixMs         int64                  `protobuf:"varint,5,opt,name=loaded_unix_ms,json=loadedUnixMs,proto3" json:"loaded_unix_ms,omitempty"`                            // When model was loaded
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ModelStats) Reset() {
	*x = ModelStats{}
	mi := &file_proto_multitenant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelStats) ProtoMessage() {}

func (x *ModelStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_multitenant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelStats.ProtoReflect.Descriptor instead.
func (*ModelStats) Descriptor() ([]byte, []int) {
	return file_proto_multitenant_proto_rawDescGZIP(), []int{5}
}

func (x *ModelStats) GetUsageCount() int64 {
	if x != nil {
		return x.UsageCount
	}
	return 0
}

func (x *ModelStats) GetLastUsedUnixMs() int64 {
	if x != nil {
		return x.LastUsedUnixMs
	}
	return 0
}

func (x *ModelStats) GetTotalInferenceTimeMs() float64 {
	if x != nil {
		return x.TotalInferenceTimeMs
	}
	return 0
}

func (x *ModelStats) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ModelStats) GetLoadedUnixMs() int64 {
	if x != nil {
		return x.LoadedUnixMs
	}
	return 0
}

type LoadModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ForceReload   bool                   `protobuf:"varint,2,opt,name=force_reload,json=forceReload,proto3" json:"force_reload,omitempty"` // Reload even if already loaded
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadModelRequest) Reset() {
	*x = LoadModelRequest{}
	mi := &file_proto_multitenant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModelRequest) ProtoMessage() {}

func (x *LoadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_multitenant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModelRequest.ProtoReflect.Descriptor instead.
func (*LoadModelRequest) Descriptor() ([]byte, []int) {
	return file_proto_multitenant_proto_rawDescGZIP(), []int{6}
}

func (x *LoadModelRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *LoadModelRequest) GetForceReload() bool {
	if x != nil {
		return x.ForceReload
	}
	return false
}

type LoadModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	LoadTimeMs    float64                `protobuf:"fixed64,3,opt,name=load_time_ms,json=loadTimeMs,proto3" json:"load_time_ms,omitempty"`
	Stats         *ModelStats            `protobuf:"bytes,4,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadModelResponse) Reset() {
	*x = LoadModelResponse{}
	mi := &file_proto_multitenant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModelResponse) ProtoMessage() {}

func (x *LoadModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_multitenant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModelResponse.ProtoReflect.Descriptor instead.
func (*LoadModelResponse) Descriptor() ([]byte, []int) {
	return file_proto_multitenant_proto_rawDescGZIP(), []int{7}
}

func (x *LoadModelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoadModelResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *LoadModelResponse) GetLoadTimeMs() float64 {
	if x != nil {
		return x.LoadTimeMs
	}
	return 0
}

func (x *LoadModelResponse) GetStats() *ModelStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type UnloadModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadModelRequest) Reset() {
	*x = UnloadModelRequest{}
	mi := &file_proto_multitenant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadModelRequest) ProtoMessage() {}

func (x *UnloadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_multitenant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadModelRequest.ProtoReflect.Descriptor instead.
func (*UnloadModelRequest) Descriptor() ([]byte, []int) {
	return file_proto_multitenant_proto_rawDescGZIP(), []int{8}
}

func (x *UnloadModelRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

type UnloadModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadModelResponse) Reset() {
	*x = UnloadModelResponse{}
	mi := &file_proto_multitenant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadModelResponse) ProtoMessage() {}

func (x *UnloadModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_multitenant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadModelResponse.ProtoReflect.Descriptor instead.
func (*UnloadModelResponse) Descriptor() ([]byte, []int) {
	return file_proto_multitenant_proto_rawDescGZIP(), []int{9}
}

func (x *UnloadModelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnloadModelResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetModelStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"` // Empty string = all models
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelStatsRequest) Reset() {
	*x = GetModelStatsRequest{}
	mi := &file_proto_multitenant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelStatsRequest) ProtoMessage() {}

func (x *GetModelStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_multitenant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelStatsRequest.ProtoReflect.Descriptor instead.
func (*GetModelStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_multitenant_proto_rawDescGZIP(), []int{10}
}

func (x *GetModelStatsRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

type GetModelStatsResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Models []*ModelInfo           `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	// Server capacity info
	MaxModels        int32 `protobuf:"varint,2,opt,name=max_models,json=maxModels,proto3" json:"max_models,omitempty"`
	LoadedModels     int32 `protobuf:"varint,3,opt,name=loaded_models,json=loadedModels,proto3" json:"loaded_models,omitempty"`
	TotalMemoryBytes int64 `protobuf:"varint,4,opt,name=total_memory_bytes,json=totalMemoryBytes,proto3" json:"total_memory_bytes,omitempty"`
	MaxMemoryBytes   int64 `protobuf:"varint,5,opt,name=max_memory_bytes,json=maxMemoryBytes,proto3" json:"max_memory_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetModelStatsResponse) Reset() {
	*x = GetModelStatsResponse{}
	mi := &file_proto_multitenant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelStatsResponse) ProtoMessage() {}

func (x *GetModelStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_multitenant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelStatsResponse.ProtoReflect.Descriptor instead.
func (*GetModelStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_multitenant_proto_rawDescGZIP(), []int{11}
}

func (x *GetModelStatsResponse) GetModels() []*ModelInfo {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *GetModelStatsResponse) GetMaxModels() int32 {
	if x != nil {
		return x.MaxModels
	}
	return 0
}

func (x *GetModelStatsResponse) GetLoadedModels() int32 {
	if x != nil {
		return x.LoadedModels
	}
	return 0
}

func (x *GetModelStatsResponse) GetTotalMemoryBytes() int64 {
	if x != nil {
		return x.TotalMemoryBytes
	}
	return 0
}

func (x *GetModelStatsResponse) GetMaxMemoryBytes() int64 {
	if x != nil {
		return x.MaxMemoryBytes
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_multitenant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_multitenant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_multitenant_proto_rawDescGZIP(), []int{12}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	CudaAvailable bool                   `protobuf:"varint,2,opt,name=cuda_available,json=cudaAvailable,proto3" json:"cuda_available,omitempty"`
	LoadedModels  int32                  `protobuf:"varint,3,opt,name=loaded_models,json=loadedModels,proto3" json:"loaded_models,omitempty"`
	MaxModels     int32                  `protobuf:"varint,4,opt,name=max_models,json=maxModels,proto3" json:"max_models,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_multitenant_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_multitenant_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_multitenant_proto_rawDescGZIP(), []int{13}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetCudaAvailable() bool {
	if x != nil {
		return x.CudaAvailable
	}
	return false
}

func (x *HealthResponse) GetLoadedModels() int32 {
	if x != nil {
		return x.LoadedModels
	}
	return 0
}

func (x *HealthResponse) GetMaxModels() int32 {
	if x != nil {
		return x.MaxModels
	}
	return 0
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_proto_multitenant_proto protoreflect.FileDescriptor

const file_proto_multitenant_proto_rawDesc = "" +
	"\n" +
	"\x17proto/multitenant.proto\x12\alipsync\"\xc5\x01\n" +
	"\x15CompositeBatchRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12#\n" +
	"\rvisual_frames\x18\x02 \x03(\x02R\fvisualFrames\x12%\n" +
	"\x0eaudio_features\x18\x03 \x03(\x02R\raudioFeatures\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x04 \x01(\x05R\tbatchSize\x12&\n" +
	"\x0fstart_frame_idx\x18\x05 \x01(\x05R\rstartFrameIdx\"\xc1\x02\n" +
	"\x16CompositeBatchResponse\x12+\n" +
	"\x11composited_frames\x18\x01 \x03(\fR\x10compositedFrames\x12*\n" +
	"\x11inference_time_ms\x18\x02 \x01(\x01R\x0finferenceTimeMs\x12*\n" +
	"\x11composite_time_ms\x18\x03 \x01(\x01R\x0fcompositeTimeMs\x12\"\n" +
	"\rtotal_time_ms\x18\x04 \x01(\x01R\vtotalTimeMs\x12!\n" +
	"\fmodel_loaded\x18\x05 \x01(\bR\vmodelLoaded\x12+\n" +
	"\x12model_load_time_ms\x18\x06 \x01(\x01R\x0fmodelLoadTimeMs\x12\x18\n" +
	"\asuccess\x18\a \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\"\x13\n" +
	"\x11ListModelsRequest\"@\n" +
	"\x12ListModelsResponse\x12*\n" +
	"\x06models\x18\x01 \x03(\v2\x12.lipsync.ModelInfoR\x06models\"\xd7\x01\n" +
	"\tModelInfo\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x16\n" +
	"\x06loaded\x18\x02 \x01(\bR\x06loaded\x12\x1d\n" +
	"\n" +
	"model_path\x18\x03 \x01(\tR\tmodelPath\x12%\n" +
	"\x0ebackground_dir\x18\x04 \x01(\tR\rbackgroundDir\x12&\n" +
	"\x0fcrop_rects_path\x18\x05 \x01(\tR\rcropRectsPath\x12)\n" +
	"\x05stats\x18\x06 \x01(\v2\x13.lipsync.ModelStatsR\x05stats\"\xd8\x01\n" +
	"\n" +
	"ModelStats\x12\x1f\n" +
	"\vusage_count\x18\x01 \x01(\x03R\n" +
	"usageCount\x12)\n" +
	"\x11last_used_unix_ms\x18\x02 \x01(\x03R\x0elastUsedUnixMs\x125\n" +
	"\x17total_inference_time_ms\x18\x03 \x01(\x01R\x14totalInferenceTimeMs\x12!\n" +
	"\fmemory_bytes\x18\x04 \x01(\x03R\vmemoryBytes\x12$\n" +
	"\x0eloaded_unix_ms\x18\x05 \x01(\x03R\floadedUnixMs\"P\n" +
	"\x10LoadModelRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12!\n" +
	"\fforce_reload\x18\x02 \x01(\bR\vforceReload\"\x90\x01\n" +
	"\x11LoadModelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12 \n" +
	"\fload_time_ms\x18\x03 \x01(\x01R\n" +
	"loadTimeMs\x12)\n" +
	"\x05stats\x18\x04 \x01(\v2\x13.lipsync.ModelStatsR\x05stats\"/\n" +
	"\x12UnloadModelRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\"E\n" +
	"\x13UnloadModelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"1\n" +
	"\x14GetModelStatsRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\"\xdf\x01\n" +
	"\x15GetModelStatsResponse\x12*\n" +
	"\x06models\x18\x01 \x03(\v2\x12.lipsync.ModelInfoR\x06models\x12\x1d\n" +
	"\n" +
	"max_models\x18\x02 \x01(\x05R\tmaxModels\x12#\n" +
	"\rloaded_models\x18\x03 \x01(\x05R\floadedModels\x12,\n" +
	"\x12total_memory_bytes\x18\x04 \x01(\x03R\x10totalMemoryBytes\x12(\n" +
	"\x10max_memory_bytes\x18\x05 \x01(\x03R\x0emaxMemoryBytes\"\x0f\n" +
	"\rHealthRequest\"\xaf\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12%\n" +
	"\x0ecuda_available\x18\x02 \x01(\bR\rcudaAvailable\x12#\n" +
	"\rloaded_models\x18\x03 \x01(\x05R\floadedModels\x12\x1d\n" +
	"\n" +
	"max_models\x18\x04 \x01(\x05R\tmaxModels\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion2\xcc\x03\n" +
	"\x12MultiTenantLipSync\x12V\n" +
	"\x13InferBatchComposite\x12\x1e.lipsync.CompositeBatchRequest\x1a\x1f.lipsync.CompositeBatchResponse\x12E\n" +
	"\n" +
	"ListModels\x12\x1a.lipsync.ListModelsRequest\x1a\x1b.lipsync.ListModelsResponse\x12B\n" +
	"\tLoadModel\x12\x19.lipsync.LoadModelRequest\x1a\x1a.lipsync.LoadModelResponse\x12H\n" +
	"\vUnloadModel\x12\x1b.lipsync.UnloadModelRequest\x1a\x1c.lipsync.UnloadModelResponse\x12N\n" +
	"\rGetModelStats\x12\x1d.lipsync.GetModelStatsRequest\x1a\x1e.lipsync.GetModelStatsResponse\x129\n" +
	"\x06Health\x12\x16.lipsync.HealthRequest\x1a\x17.lipsync.HealthResponseB\x1dZ\x1bgo-multitenant-server/protob\x06proto3"

var (
	file_proto_multitenant_proto_rawDescOnce sync.Once
	file_proto_multitenant_proto_rawDescData []byte
)

func file_proto_multitenant_proto_rawDescGZIP() []byte {
	file_proto_multitenant_proto_rawDescOnce.Do(func() {
		file_proto_multitenant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_multitenant_proto_rawDesc), len(file_proto_multitenant_proto_rawDesc)))
	})
	return file_proto_multitenant_proto_rawDescData
}

var file_proto_multitenant_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_multitenant_proto_goTypes = []any{
	(*CompositeBatchRequest)(nil),  // 0: lipsync.CompositeBatchRequest
	(*CompositeBatchResponse)(nil), // 1: lipsync.CompositeBatchResponse
	(*ListModelsRequest)(nil),      // 2: lipsync.ListModelsRequest
	(*ListModelsResponse)(nil),     // 3: lipsync.ListModelsResponse
	(*ModelInfo)(nil),              // 4: lipsync.ModelInfo
	(*ModelStats)(nil),             // 5: lipsync.ModelStats
	(*LoadModelRequest)(nil),       // 6: lipsync.LoadModelRequest
	(*LoadModelResponse)(nil),      // 7: lipsync.LoadModelResponse
	(*UnloadModelRequest)(nil),     // 8: lipsync.UnloadModelRequest
	(*UnloadModelResponse)(nil),    // 9: lipsync.UnloadModelResponse
	(*GetModelStatsRequest)(nil),   // 10: lipsync.GetModelStatsRequest
	(*GetModelStatsResponse)(nil),  // 11: lipsync.GetModelStatsResponse
	(*HealthRequest)(nil),          // 12: lipsync.HealthRequest
	(*HealthResponse)(nil),         // 13: lipsync.HealthResponse
}
var file_proto_multitenant_proto_depIdxs = []int32{
	4,  // 0: lipsync.ListModelsResponse.models:type_name -> lipsync.ModelInfo
	5,  // 1: lipsync.ModelInfo.stats:type_name -> lipsync.ModelStats
	5,  // 2: lipsync.LoadModelResponse.stats:type_name -> lipsync.ModelStats
	4,  // 3: lipsync.GetModelStatsResponse.models:type_name -> lipsync.ModelInfo
	0,  // 4: lipsync.MultiTenantLipSync.InferBatchComposite:input_type -> lipsync.CompositeBatchRequest
	2,  // 5: lipsync.MultiTenantLipSync.ListModels:input_type -> lipsync.ListModelsRequest
	6,  // 6: lipsync.MultiTenantLipSync.LoadModel:input_type -> lipsync.LoadModelRequest
	8,  // 7: lipsync.MultiTenantLipSync.UnloadModel:input_type -> lipsync.UnloadModelRequest
	10, // 8: lipsync.MultiTenantLipSync.GetModelStats:input_type -> lipsync.GetModelStatsRequest
	12, // 9: lipsync.MultiTenantLipSync.Health:input_type -> lipsync.HealthRequest
	1,  // 10: lipsync.MultiTenantLipSync.InferBatchComposite:output_type -> lipsync.CompositeBatchResponse
	3,  // 11: lipsync.MultiTenantLipSync.ListModels:output_type -> lipsync.ListModelsResponse
	7,  // 12: lipsync.MultiTenantLipSync.LoadModel:output_type -> lipsync.LoadModelResponse
	9,  // 13: lipsync.MultiTenantLipSync.UnloadModel:output_type -> lipsync.UnloadModelResponse
	11, // 14: lipsync.MultiTenantLipSync.GetModelStats:output_type -> lipsync.GetModelStatsResponse
	13, // 15: lipsync.MultiTenantLipSync.Health:output_type -> lipsync.HealthResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_multitenant_proto_init() }
func file_proto_multitenant_proto_init() {
	if File_proto_multitenant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_multitenant_proto_rawDesc), len(file_proto_multitenant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_multitenant_proto_goTypes,
		DependencyIndexes: file_proto_multitenant_proto_depIdxs,
		MessageInfos:      file_proto_multitenant_proto_msgTypes,
	}.Build()
	File_proto_multitenant_proto = out.File
	file_proto_multitenant_proto_goTypes = nil
	file_proto_multitenant_proto_depIdxs = nil
}
